version: '3.8'
#commentT
services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    container_name: fossbilling_server
    restart: always # Ensures the container restarts automatically in case of failure
    ports:
      - "8081:80" # Maps port 80 inside the container to port 8081 on the host machine
    volumes: 
      - fossbilling_data:/var/www/html # Persists FOSSBilling data across container restarts

  db:
    image: mysql:5.7
    container_name: fossbilling_db
    restart: always # Ensures the database container restarts automatically
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: fossbilling
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] #Runs a MySQL health check every 10s, retries 5 times, and waits 20s before the first check
      interval: 10s
      retries: 5
      start_period: 20s  
    volumes:
      - db_data:/var/lib/mysql # Persists MySQL data across container restarts

volumes: # Define persistent volumes for data storage
  fossbilling_data:
  db_data:

