name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for Containers to Start
        run: sleep 20  # Adjust if needed

      - name: Check Running Containers
        run: docker ps

      - name: Test Web Service
        run: curl -f http://128.251.187.54:8081 || exit 1

      - name: Stop and Clean Up
        run: docker-compose down
